name: 'build_the_docs'

on:
  push:
    branches:
      - master

jobs:

  publish_docs:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: buildthedocs/btd@v0
      with:
        token: ${{ github.token }}

    - uses: actions/upload-artifact@v2
      with:
        name: source
        path: source/_build/html
