---
name: build_the_docs_upstream

on:
  push:
    branches:
      - upstream

jobs:

  publish_docs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: buildthedocs/btd@v0
        with:
          config: '.btd-upstream.yml'

      - uses: actions/upload-artifact@v2
        with:
          name: docs_upstream
          path: docs/_build/html
